### ISSUE TITLE
求可用的用户名密码测试

### ISSUE THREAD

**Issue by ixxxxxx** [AnyLifeZLB/AndroidAppFrameWork#17]
貌似默认的用户名密码不能用了，我这里登录显示`账户或者密码错误 code=201`
想登录下看看这个App的界面以及功能，能否给个测试账户呢？

**Comment by AnyLifeZLB** [comment]
@ixxxxxx 你先更新一下代码，等我有时间整理代码后去除OAUTH

**Comment by ixxxxxx** [comment]
谢谢，刚看到，已经运行起来了。
